/**
 * Migration Generator
 * Produces LLM-ready markdown migration prompts from dependency analysis data
 */

import * as path from "node:path";
import type { DependencyAnalysis, SymbolUsage } from "../types/index.js";
import { targetSupports } from "../utils/tsconfig-resolver.js";
import type {
  MigrationContext,
  MigrationOutput,
  MigrationTemplate,
  SymbolMigrationRule,
} from "./types.js";

interface ResolvedSymbol {
  usage: SymbolUsage;
  rule: SymbolMigrationRule;
}

/**
 * Generate a migration prompt for a given dependency analysis.
 * Returns a markdown document ready to paste into Claude Code or any LLM.
 */
export function generateMigration(
  analysis: DependencyAnalysis,
  context: MigrationContext,
  template: MigrationTemplate
): MigrationOutput {
  const resolved = resolveSymbolRules(analysis, template);
  const outputPath = buildOutputPath(analysis.name);
  const markdown = buildMarkdown(analysis, context, template, resolved);

  return {
    markdown,
    outputPath,
    metadata: {
      packageName: analysis.name,
      symbolCount: analysis.symbolsUsed.length,
      fileCount: analysis.fileCount,
      targetEcmaVersion: context.tsconfigTarget,
    },
  };
}

// ============================================================================
// Internal helpers
// ============================================================================

function resolveSymbolRules(
  analysis: DependencyAnalysis,
  template: MigrationTemplate
): ResolvedSymbol[] {
  const result: ResolvedSymbol[] = [];

  for (const usage of analysis.symbolsUsed) {
    const rule = template.symbols[usage.symbol] ?? template.symbols["default"];
    if (rule) {
      result.push({ usage, rule: { ...rule, symbol: usage.symbol } });
    }
  }

  return result;
}

function buildOutputPath(packageName: string): string {
  const safe = packageName.replace(/[^a-z0-9@/-]/gi, "-").replace(/^@/, "");
  return `.dep-scope/migrate-${safe}.md`;
}

function buildMarkdown(
  analysis: DependencyAnalysis,
  context: MigrationContext,
  template: MigrationTemplate,
  resolved: ResolvedSymbol[]
): string {
  const sections: string[] = [];

  sections.push(buildHeader(analysis, context));
  sections.push(buildAuditSummary(analysis, context));

  if (resolved.length === 0) {
    sections.push(buildNoTemplateSection(analysis));
  } else {
    sections.push(buildRefactoringPlan(resolved, context));
  }

  sections.push(buildSteps(analysis, context));
  sections.push(buildVerificationChecklist(analysis, context));
  sections.push(buildRollback());

  if (template.globalCaveats?.length) {
    sections.push(buildGlobalCaveats(template.globalCaveats));
  }

  return sections.join("\n\n") + "\n";
}

function buildHeader(analysis: DependencyAnalysis, context: MigrationContext): string {
  return `# Migrate away from \`${analysis.name}\`

> Generated by dep-scope · ${new Date().toISOString().split("T")[0]} · Target: ${context.tsconfigTarget}

You are a TypeScript/JavaScript expert. Your task is to **remove \`${analysis.name}\` from this project** by replacing its usages with native equivalents or minimal custom utilities. Follow the plan below exactly, verifying the build and tests pass after each symbol replacement.`;
}

function buildAuditSummary(analysis: DependencyAnalysis, context: MigrationContext): string {
  const usedPercent =
    analysis.totalSymbolsAvailable
      ? `${((analysis.symbolsUsed.length / analysis.totalSymbolsAvailable) * 100).toFixed(1)}% of exported API`
      : `${analysis.symbolsUsed.length} symbol${analysis.symbolsUsed.length !== 1 ? "s" : ""}`;

  const symbolList = analysis.symbolsUsed.map((s) => `\`${s.symbol}\``).join(", ");

  return `## Audit summary

| Field            | Value                                  |
| ---------------- | -------------------------------------- |
| Package          | \`${analysis.name}\` ${analysis.version} |
| Symbols used     | ${symbolList} (${usedPercent})         |
| Files affected   | ${analysis.fileCount}                  |
| Import style     | ${analysis.importStyle}                |
| TypeScript target | ${context.tsconfigTarget}             |
| Framework        | ${context.framework ?? "unknown"}      |`;
}

function buildRefactoringPlan(resolved: ResolvedSymbol[], context: MigrationContext): string {
  const steps = resolved.map((r, i) => buildSymbolSection(r, i + 1, context));
  return `## Refactoring plan\n\n${steps.join("\n\n---\n\n")}`;
}

function buildSymbolSection(
  { usage, rule }: ResolvedSymbol,
  index: number,
  context: MigrationContext,
): string {
  const nativeSupported = targetSupports(context.tsconfigTarget, rule.minEcmaVersion);
  const lines: string[] = [];

  // "default" means the whole package was imported — show the package name as the label
  const displaySymbol = usage.symbol === "default" ? `${rule.symbol === "default" ? "default import" : usage.symbol}` : usage.symbol;
  lines.push(`### ${index}. Replace \`${displaySymbol}\``);
  lines.push(`**Used in ${usage.count} import${usage.count !== 1 ? "s" : ""}** across ${usage.locations.length} location${usage.locations.length !== 1 ? "s" : ""}:`);

  // List unique files with line numbers
  const fileLines = buildLocationList(usage, context.projectPath);
  lines.push(fileLines);

  lines.push(`**Native replacement:** ${rule.nativeReplacement}`);

  if (!nativeSupported && rule.polyfillFallback) {
    lines.push(
      `> ⚠️ Your target (${context.tsconfigTarget}) is below the required minimum (${rule.minEcmaVersion}). Use the fallback below instead.\n`
    );
    lines.push("```ts\n" + rule.polyfillFallback + "\n```");
  } else {
    if (!nativeSupported) {
      lines.push(
        `> ⚠️ Minimum required: ${rule.minEcmaVersion} — your target is ${context.tsconfigTarget}. Verify runtime support.`
      );
    }
    lines.push("```ts\n" + rule.example + "\n```");
  }

  if (rule.caveats.length > 0) {
    lines.push("**Caveats:**");
    lines.push(rule.caveats.map((c) => `- ${c}`).join("\n"));
  }

  return lines.join("\n\n");
}

function buildLocationList(usage: SymbolUsage, projectPath: string): string {
  // Deduplicate by file and show up to 10 locations
  const byFile = new Map<string, number[]>();
  for (const loc of usage.locations) {
    const lines = byFile.get(loc.file) ?? [];
    lines.push(loc.line);
    byFile.set(loc.file, lines);
  }

  const entries: string[] = [];
  for (const [file, lineNumbers] of byFile) {
    const relative = file.startsWith("/") ? path.relative(projectPath, file) : file;
    const lineRef = lineNumbers.length === 1
      ? `:${lineNumbers[0]}`
      : `:${lineNumbers.slice(0, 5).join(", ")}${lineNumbers.length > 5 ? "…" : ""}`;
    entries.push(`- \`${relative}${lineRef}\``);
  }

  if (entries.length > 10) {
    const shown = entries.slice(0, 10);
    return shown.join("\n") + `\n- *(and ${entries.length - 10} more files)*`;
  }

  return entries.join("\n");
}

function buildNoTemplateSection(analysis: DependencyAnalysis): string {
  const symbolList = analysis.symbolsUsed.map((s) => `\`${s.symbol}\``).join(", ") || "unknown";
  return `## Refactoring plan

No specific rules are defined for the symbols used (${symbolList}). Follow the general approach:

1. Search for all imports: \`grep -r "from '${analysis.name}'" src/\`
2. For each usage, identify the purpose and find a native or minimal equivalent
3. Replace and test incrementally

The dep-scope template library does not yet cover \`${analysis.name}\`. Consider contributing a template!`;
}

function buildSteps(analysis: DependencyAnalysis, context: MigrationContext): string {
  const pm = context.packageManager ?? "npm";
  const runCmd = pm === "npm" ? "npm run" : pm;
  const uninstallCmd = pm === "bun" ? "bun remove" : `${pm} uninstall`;
  const branchName = `refactor/remove-${analysis.name.replace(/[^a-z0-9-]/gi, "-")}`;

  return `## Steps

1. **Create a dedicated branch** before starting:
   \`\`\`bash
   git checkout -b ${branchName}
   \`\`\`

2. **Work through each symbol** in the "Refactoring plan" above, one at a time.

3. **After each symbol replacement**, run:
   \`\`\`bash
   ${runCmd} build && ${runCmd} test
   \`\`\`
   Fix any failures before moving to the next symbol.

4. **Once all symbols are replaced**, remove the package:
   \`\`\`bash
   ${uninstallCmd} ${analysis.name}
   \`\`\`

5. **Verify no remaining imports**:
   \`\`\`bash
   grep -r "from '${analysis.name}'\|from \\"${analysis.name}\\"\|require('${analysis.name}')" src/ || echo "Clean!"
   \`\`\`

6. **Final build and test pass** — \`${runCmd} build && ${runCmd} test\`.`;
}

function buildVerificationChecklist(analysis: DependencyAnalysis, context: MigrationContext): string {
  const pm = context.packageManager ?? "npm";
  const runCmd = pm === "npm" ? "npm run" : pm;
  const uninstallCmd = pm === "bun" ? "bun remove" : `${pm} uninstall`;
  const installCmd = pm === "bun" ? "bun install" : `${pm} install`;

  return `## Verification checklist

- [ ] Branch \`refactor/remove-${analysis.name.replace(/[^a-z0-9-]/gi, "-")}\` created
- [ ] All \`${analysis.name}\` imports removed from source files
- [ ] No remaining references: \`grep -r "${analysis.name}" src/\` returns nothing
- [ ] \`${runCmd} build\` passes with no TypeScript errors
- [ ] \`${runCmd} test\` passes with all tests green
- [ ] \`package.json\` no longer lists \`${analysis.name}\` in dependencies
- [ ] Lockfile updated (\`${installCmd}\` run after \`${uninstallCmd} ${analysis.name}\`)`;
}

function buildRollback(): string {
  return `## Rollback

If anything breaks and you want to start over:

\`\`\`bash
git checkout main -- .
\`\`\`

Or to keep uncommitted changes and just undo the package removal:

\`\`\`bash
git stash
\`\`\``;
}

function buildGlobalCaveats(caveats: string[]): string {
  return `## General notes\n\n${caveats.map((c) => `> ${c}`).join("\n>\n")}`;
}
